services:
  mira-api:
    build: ./backend
    container_name: mira-api
    ports:
      - "8088:8000"          # снаружи 8088, внутри 8000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  # доступ к Docker демону
      - ./mira-data:/data
    restart: unless-stopped
